/// Libellés FR des extensions Pokémon (code PTCGO / API).
abstract final class PokemonSetLabelsFr {
  static const _byCode = {
  // Méga-Évolution
    'MEG': 'Méga-Évolution',
    'MEE': 'Énergies Méga-Évolution',
    'MEP': 'Promos Méga-Évolution',
    'CRI': 'Chaos Ascendant',
    'POR': 'Équilibre Parfait',
    'ASC': 'Héros Transcendants',
    'PFL': 'Flammes Fantasmagoriques',
  // Écarlate et Violet
    'BLK': 'Foudre Noire',
    'WHT': 'Flamme Blanche',
    'DRI': 'Rivalités Destinées',
    'JTG': 'Aventures Ensemble',
    'PRE': 'Évolutions Prismatiques',
    'SSP': 'Étincelles Déferlantes',
    'SCR': 'Couronne Stellaire',
    'SFA': 'Fable Nébuleuse',
    'TWM': 'Mascarade Crépusculaire',
    'TEF': 'Forces Temporelles',
    'PAF': 'Destinées de Paldea',
    'PAR': 'Faille Paradoxe',
    'MEW': '151',
    'OBF': 'Flammes Obsidiennes',
    'PAL': 'Évolutions à Paldea',
    'SVI': 'Écarlate et Violet',
    'SVE': 'Énergies Écarlate et Violet',
    'SVP': 'Promos Écarlate et Violet',
  // Épée et Bouclier
    'CRZ': 'Zénith Suprême',
    'SIT': 'Tempête Argentée',
    'LOR': 'Origine Perdue',
    'PGO': 'Pokémon GO',
    'ASR': 'Astres Radieux',
    'BRS': 'Stars Étincelantes',
    'FST': 'Poing de Fusion',
    'CEL': 'Célébrations',
    'EVS': 'Évolution Céleste',
    'CRE': 'Règne de Glace',
    'SWSH5': 'Styles de Combat',
    'SWSH45': 'Destinées Radieuses',
    'SWSH4': 'Voltage Éclatant',
    'SWSH35': 'La Voie du Maître',
    'SWSH3': 'Ténèbres Embrasées',
    'SWSH2': 'Clash des Rebelles',
    'SWSH1': 'Épée et Bouclier',
    'PRSWSH': 'Promos Épée et Bouclier',
  // Soleil et Lune
    'SM12': 'Éclipse Cosmique',
    'SM115': 'Destinées Occultes',
    'SM11': 'Harmonie des Esprits',
    'SM10': 'Alliance Infaillible',
    'SM09': 'Duo de Choc',
    'SM08': 'Tonnerre Perdu',
    'SM75': 'Majesté des Dragons',
    'SM07': 'Tempête Céleste',
    'SM06': 'Lumière Interdite',
    'SM05': 'Ultra-Prisme',
    'SM04': 'Invasion Carmin',
    'SLE': 'Légendes Brillantes',
    'SM03': 'Ombres Ardentes',
    'SM02': 'Gardiens Ascendants',
    'SM01': 'Soleil et Lune',
    'PRSM': 'Promos Soleil et Lune',
  // XY
    'EVO': 'Évolutions',
    'STS': 'Offensive Vapeur',
    'FAC': 'Impact des Destins',
    'GNR': 'Générations',
    'BKP': 'Rupture Turbo',
    'BKT': 'Impulsion Turbo',
    'AOR': 'Origines Antiques',
    'ROS': 'Ciel Rugissant',
    'DCR': 'Double Danger',
    'PRC': 'Primo-Choc',
    'PHF': 'Vigueur Spectrale',
    'FFI': 'Poings Furieux',
    'FLF': 'Étincelles',
    'XY': 'XY',
    'KSS': 'Bienvenue à Kalos',
    'PRXY': 'Promos X&Y',
  // Noir et Blanc
    'LTR': 'Legendary Treasures',
    'PLB': 'Explosion Plasma',
    'PLF': 'Glaciation Plasma',
    'PLS': 'Tempête Plasma',
    'BCR': 'Frontières Franchies',
    'DRV': 'Coffre des Dragons',
    'DRX': 'Dragons Exaltés',
    'DEX': 'Explorateurs Obscurs',
    'NXD': 'Destinées Futures',
    'NVI': 'Nobles Victoires',
    'EPO': 'Pouvoirs Émergents',
    'BLW': 'Noir et Blanc',
    'PRBW': 'Promos Black Star Noir & Blanc',
    'CL': "L'appel des légendes",
  // HGSS
    'TM': 'HS : Triomphe',
    'UD': 'HS : Indomptable',
    'UL': 'HS : Déchaînement',
    'HGSS': 'HeartGold SoulSilver',
    'PRHS': 'Promos Black Star HeartGold SoulSilver',
  // Platine
    'AR': 'Platine : Arceus',
    'SV': 'Platine : Vainqueurs Suprêmes',
    'RR': 'Platine : Rivaux Émergeants',
    'PT': 'Platine',
  };

  /// Nom FR si le code est connu, sinon le nom API.
  static String setLabel(String? code, String apiName) {
    if (code == null || code.isEmpty) return apiName;
    final upper = code.toUpperCase();
    return _byCode[upper] ?? apiName;
  }
}
